code_links/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :conversations do
    member do
      post :trash
    end

    resources :messages


  end
  resources :posts do
    	resources :comments
  end
  resources :controllers
  get 'scaffold/Conversations'
  resources :users, only: [:index]
  root to: "pages#home"
  get 'sessions/new'
  get 'pages/home'
  get 'pages/display'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile', to: 'users#profile'
  get '/lessons', to: 'pages#lessons'
  get '/thehub', to: 'pages#forum'
  get '/search', to: 'pages#search'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 		'/login', 		to: 'sessions#new'
  post 		'/login', 	to: 'sessions#create'
  get 		'/logout', 	to: 'sessions#destroy'

  delete 		'/logout', 	to: 'sessions#destroy'
end

code_links/app/models/conversation.rb
class Conversation < ApplicationRecord
end

code_links/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    if tutor?
      @recipients = User.all - [current_user] - tutors
    else
      @recipients = User.all - [current_user] - guardians

    end


  end

  def create
    recipient = User.find(params[:user_id])
    r = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(r.conversation)
  end

  def trash

    flash[:danger] = 'CONVERSATION DELETED'
    @conversation = current_user.mailbox.conversations.find(params[:id])
    @conversation.delete
    redirect_to :conversations
  end
end

code_links/app/helpers/conversations_helper.rb
module ConversationsHelper
end

code_links/app/views/conversations/index.html.erb
<div class="card-hub-main">

<h1>All Conversations</h1>
<%  @conversations.each do |c| %>
  <% unless c.is_trashed?(c)%>
    <div class="hub-box">
      <div class="subject-link">

        <%= link_to c.subject, conversation_path(c)%>
      </div>
      <div class="trash">
        <%= link_to image_tag('trash.png'), trash_conversation_path(c), method: :post, data: { confirm: 'Are you sure?' } %>

      </div>
    </div>

  <%end %>

<%end%>
<br>
<div class="new">
  <%= link_to "New Conversation", new_conversation_path %>

</div>
</div>

code_links/app/views/conversations/new.html.erb
<div class="new-mssg">
  <h1>New Message</h1>
  <%= form_tag conversations_path, method: :post do %>
  <div class="send-to">
    Recipient:
    <br>
    <%= select_tag :user_id, options_from_collection_for_select(@recipients , :id, :name) %>
  </div>

  <div class="subject">
     <%= text_field_tag :subject,nil , placeholder: "Subject" %>
  </div>

  <div class="body">
     <%= text_area_tag :body, nil, placeholder: "Body" %>
  </div>
<br>
  <%= submit_tag "Send" %>

  <%end %>
</div>

code_links/app/views/conversations/show.html.erb
<div class="card-hub">

<h1><%=@conversation.subject%></h1>


<%  @conversation.receipts_for(current_user).each do |r| %>

    <% if r.message.sender.name.eql?(current_user.name) %>
    <div class="">
      <div class="name">
        <%=r.message.sender.name%>:
      </div>
      <%= r.message.body%>
      <br>
      <div class="created">
        <%=r.created_at%>
      </div>
      <br>
    </div>

    <%else %>
    <div class="">
      <div class="name">
        <%=r.message.sender.name%>:
      </div>
      <%= r.message.body%>
      <br>
      <div class="created">
        <%=r.created_at%>
      </div>
      <br>
    </div>
    <% end %>



<%end %>

<div class="">
  <%= form_tag conversation_messages_path(@conversation), method: :post do %>
    <div class="body">
      <%= text_area_tag :body %>
    </div>
    <%= submit_tag "Respond" %>
  <% end %>

</div>
<br>
<span class="back-to">  <%= link_to 'Back to Inbox',conversations_path %>
</span>


</div>