code_links/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :conversations do
    member do
      post :trash
    end

    resources :messages


  end
  resources :posts do
    	resources :comments
  end
  resources :controllers
  get 'scaffold/Conversations'
  resources :users, only: [:index]
  root to: "pages#home"
  get 'sessions/new'
  get 'pages/home'
  get 'pages/display'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile', to: 'users#profile'
  get '/lessons', to: 'pages#lessons'
  get '/thehub', to: 'pages#forum'
  get '/search', to: 'pages#search'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 		'/login', 		to: 'sessions#new'
  post 		'/login', 	to: 'sessions#create'
  get 		'/logout', 	to: 'sessions#destroy'

  delete 		'/logout', 	to: 'sessions#destroy'
end

code_links/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  VALIDATE_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,  presence:   true,   length: {maximum:  150},
  uniqueness:  {case_sensitive:  false}
  has_secure_password
  validates   :password, length: {minimum:  8}
  has_many :posts
  has_many :comments

  acts_as_messageable

end

code_links/app/controllers/users_controller.rb
class UsersController < ApplicationController
#extend Mailboxer::Models::Messageable::ActiveRecordExtension
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_account, only: :destroy
  #acts_as_messageable
  # GET /users
  # GET /users.json

  def index
    @users = User.all
  end

  def current_user?(user)
    user == current_user
  end
  # GET /users/1
  # GET /users/1.json
  def show
  end

  def get_user(set_user)

  end

  def profile
    @user = current_user
  end

  # GET /users/new
  def new
    @user = User.new
    @account_type_option = {}
    @account_type_option["Parent"] = "Parent"
    @account_type_option["Legal Guardian"] = "Legal Guardian"
    @account_type_option["Tutor"] = "Tutor"


  end

  # GET /users/1/edit
  def edit
    @account_type_option = {}
    @account_type_option["Parent"] = "Parent"
    @account_type_option["Legal Guardian"] = "Legal Guardian"
    @account_type_option["Tutor"] = "Tutor"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @account_type_option = {}
    @account_type_option["Parent"] = "Parent"
    @account_type_option["Legal Guardian"] = "Legal Guardian"
    @account_type_option["Tutor"] = "Tutor"
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user }
        flash[:success] = 'ACCOUNT CREATED'
        format.json { render :show, status: :created, location: @user }
        log_in @user
      else
        format.html { render :new }
        flash[:danger] = 'Error: fill in all fields'
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @account_type_option = {}
    @account_type_option["Parent"] = "Parent"
    @account_type_option["Legal Guardian"] = "Legal Guardian"
    @account_type_option["Tutor"] = "Tutor"
    @user = current_user
    if @user.update_attributes(user_params)
        flash[:success] = "Account was successfully updated."
        redirect_to profile_path
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, alert: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone_number, :city, :about_me,:account_type, :password, :password_confirmation)
    end

    def admin_account
      redirect_to(root_url) unless current_user.admin?
    end
end

code_links/app/helpers/users_helper.rb
module UsersHelper
  def tutor?
    current_user.account_type.eql?("Tutor")
  end

  def tutors
    @tutors = []
    @users = User.all
    if @users
      @users.each do |u|
        if u.account_type.eql?("Tutor")
          @tutors.push u
        end
      end
    end
    @tutors
  end

  def guardians
    @guardians = []
    @users = User.all
    if @users
      User.all.each do |u|
        unless u.account_type.eql?("Tutor")
          @guardians.push u
        end
      end
    end
    @guardians
  end



end

code_links/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

	  <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>

      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: 'form-control' %>

      <%= f.label :account_type %>
      <br>
      <%= f.select :account_type, @account_type_option %>
<br>
      <br>
      <%= f.label :about_me %>
      <%= f.text_area :about_me, class: 'form-control' %>

      <%= f.label  :password %>
      <%= f.password_field  :password, class:  'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field  :password_confirmation, class: 'form-control' %>
<br>
      <%= f.submit  "Save Account", class: "btn btn-primary" %>

    <% end %>

code_links/app/views/users/edit.html.erb
<h1>Editing User</h1>



<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

code_links/app/views/users/index.html.erb
<% if current_user.try(:admin?) %>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Account Type</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.account_type %></td>
        <td><%= user.city %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New User', new_user_path %>
<% else %>
 <p id="not-found"> PAGE NOT FOUND </p>
<% end %>

code_links/app/views/users/new.html.erb
<div class="new-user">
  <h1>New User</h1>
  <%= render 'form', user: @user %>

</div>


<%link_to 'Back', users_path %>

code_links/app/views/users/profile.html.erb
<div class="browse-g">
  <h1>My Profile</h1>
<br>
  <p>
    <strong>Full Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Contact Information:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @user.city %>
  </p>
  <p>
    <strong>Account Type:</strong>
    <%= @user.account_type %>
  </p>
  <p>
    <strong>About Me:</strong>
    <%= @user.about_me %>
  </p>

  <td><%= link_to 'Edit', edit_user_path(@user) %></td>

</div>

code_links/app/views/users/show.html.erb
<div class="browse-g">
  <p>
    <strong>Full Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Contact Information:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @user.city %>
  </p>
  <p>
    <strong>Account Type:</strong>
    <%= @user.account_type %>
  </p>
  <p>
    <strong>About Me:</strong>
    <%= @user.about_me %>
  </p>

  <td><%= link_to 'Message', new_conversation_path %></td>

</div>