code_links/config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :conversations do
    member do
      post :trash
    end

    resources :messages


  end
  resources :posts do
    	resources :comments
  end
  resources :controllers
  get 'scaffold/Conversations'
  resources :users, only: [:index]
  root to: "pages#home"
  get 'sessions/new'
  get 'pages/home'
  get 'pages/display'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/profile', to: 'users#profile'
  get '/lessons', to: 'pages#lessons'
  get '/thehub', to: 'pages#forum'
  get '/search', to: 'pages#search'

  get '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get 		'/login', 		to: 'sessions#new'
  post 		'/login', 	to: 'sessions#create'
  get 		'/logout', 	to: 'sessions#destroy'

  delete 		'/logout', 	to: 'sessions#destroy'
end

code_links/app/views/layouts/_footer.html.erb
<footer class=”footer”>
  <div class="bottom-text-first">
    <small>
       Designed by: Erica Pereira 2020
    </small>
  </div>

<nav >
<ul>

   <li><%= link_to "Home", controller: "pages", action: "home" %></li>
   <li><a href=”http://www.depauw.edu”>DePauw</a></li>
</ul>
</nav>
</footer>

code_links/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

      <div class="container-fluid">
        <nav>
          <div class="logo">
            <%= link_to image_tag( "logo1.jpg", alt: "ManBearPig", id: "logo" ), "https://www.youtube.com/watch?v=0AW4nSq0hAc", target: "_blank" %>
            </div>
          <ul class= "nav navbar-nav navbar-right">
            <li id="home"><%= link_to "Home", controller: "pages", action: "home" %></li>
            <% if logged_in? %>
                <li><%= link_to "My Profile", profile_path %></li>

                <% if tutor?%>

                  <li><%= link_to "Lessons", lessons_path %></li>
                  <li><%= link_to "The Hub", posts_path %></li>


                <%end%>
                <li><%= link_to "Search", search_path %></li>

                <% @inbox = "Inbox <span id='move-up'>#{current_messages}</span>".html_safe %>
                <li><%= link_to "Inbox", conversations_path(current_user) %></li>
                <li><span id='move-up'><%=current_messages%> </span></li>
                <% if current_user.try(:admin?) %>
                <li><%= link_to 'Admin Settings', users_path %> </li>
                <% end %>
                <li><%= link_to "Log out", logout_path, method: :delete %></li>

               <% else %>
                  <li><%= link_to "Log in", login_path %></li>
              <% end %>

          </ul>
          </nav>

      </div>



</header>

code_links/app/views/layouts/_header2.html.erb
<div class="d-flex">
  <div class="dropdown mr-1">
    <button type="button" class="btn btn-secondary dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="10,20">
      Offset
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
    </div>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-secondary">Reference</button>
    <button type="button" class="btn btn-secondary dropdown-toggle dropdown-toggle-split" id="dropdownMenuReference" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-reference="parent">
      <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
    </div>
  </div>
</div>

code_links/app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100;0,400;0,700;1,600&display=swap" rel="stylesheet">
<% favicon_link_tag "logo1.jpg" %>
<html>
  <head>
    <title>CodeLinks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/header' %>

  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type%>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>

</html>